version: "3.9"

services:
  jupyter:
    image: jupyter/scipy-notebook:latest
    container_name: jupyter-notebook
    ports:
      - "9999:8888"
    volumes:
      - ./notebooks:/home/jovyan/work
      - ./requirements.txt:/tmp/requirements.txt
    environment:
      - JUPYTER_TOKEN=ml1234
    command: >
      bash -c "pip install --no-cache-dir -r /tmp/requirements.txt &&
               start-notebook.sh --NotebookApp.token=$JUPYTER_TOKEN"
    restart: unless-stopped

